on: [push, pull_request]

name: 'Build the Axyl ISO'

jobs:
  build-iso:

    runs-on: ubuntu-latest
    container:
      image: archlinux

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Update and install archiso
      run: pacman -Syu archiso sudo --noconfirm --needed

    - name: Build the iso
      run: bash ./installation-scripts/build.sh

    - name: Check if the iso exists
      run: ls /github/home/Axyl-Iso
